export type Lead = {
  slug: string;
  name: string;
  alias: string;
  sector: string;
  location: string;
  address: string;
  stage: "New" | "Underwriting" | "Approved" | "Rejected";
  bankableScore: number;
  pd: number;
  recommendedLimit: number;
  creditworthiness: string;
  acceptance: number;
  exposure: number;
  ltrRank: number;
  entityConfidence: number;
  velocity: string;
  revenue: number;
  volatility: string;
  kyc: { stabilityMonths: number; locationStability: number; identityConfidence: number; deviceClean: number };
  pnl: { inflowTTM: string; momoTrend: string; expenses: { label: string; value: number }[] };
  shap: { label: string; impact: number }[];
};

export const leads: Lead[] = [
  {
    slug: "ets-ibrahim",
    name: "Ets Ibrahim",
    alias: "Hajj Brahim",
    sector: "Grocer / FMCG",
    location: "Derb Omar",
    address: "12 Rue Ibn Sina, Casablanca",
    stage: "New",
    bankableScore: 782,
    pd: 0.018,
    recommendedLimit: 20000,
    creditworthiness: "A",
    acceptance: 0.82,
    exposure: 18500,
    ltrRank: 1,
    entityConfidence: 0.91,
    velocity: "+18% MoM",
    revenue: 9800000,
    volatility: "Low",
    kyc: { stabilityMonths: 12.4, locationStability: 0.93, identityConfidence: 0.94, deviceClean: 0.97 },
    pnl: {
      inflowTTM: "9.8M MAD",
      momoTrend: "+6.2%",
      expenses: [
        { label: "Inventory / Suppliers", value: 47 },
        { label: "Rent & Utilities", value: 18 },
        { label: "Staff", value: 12 },
        { label: "Logistics / Delivery", value: 9 },
        { label: "Personal draws", value: 6 },
      ],
    },
    shap: [
      { label: "Income stability", impact: 40 },
      { label: "12m history depth", impact: 28 },
      { label: "Daily app discipline", impact: 22 },
      { label: "Volatility", impact: -18 },
      { label: "Late utility bills", impact: -12 },
    ],
  },
  {
    slug: "salon-amal",
    name: "Salon Amal",
    alias: "Coiffure Amal",
    sector: "Beauty",
    location: "Maarif",
    address: "44 Bd Anfa, Casablanca",
    stage: "Underwriting",
    bankableScore: 731,
    pd: 0.026,
    recommendedLimit: 12000,
    creditworthiness: "B+",
    acceptance: 0.74,
    exposure: 9200,
    ltrRank: 2,
    entityConfidence: 0.87,
    velocity: "+9% MoM",
    revenue: 6400000,
    volatility: "Medium",
    kyc: { stabilityMonths: 10.8, locationStability: 0.89, identityConfidence: 0.91, deviceClean: 0.92 },
    pnl: {
      inflowTTM: "6.4M MAD",
      momoTrend: "+4.1%",
      expenses: [
        { label: "Supplies", value: 35 },
        { label: "Rent & Utilities", value: 24 },
        { label: "Staff", value: 14 },
        { label: "Marketing", value: 8 },
        { label: "Personal draws", value: 6 },
      ],
    },
    shap: [
      { label: "Consistency", impact: 24 },
      { label: "History depth", impact: 18 },
      { label: "Engagement", impact: 12 },
      { label: "Volatility", impact: -10 },
      { label: "Late bills", impact: -8 },
    ],
  },
  {
    slug: "atlas-gsm",
    name: "Eurl Atlas Phone",
    alias: "Atlas GSM",
    sector: "Mobile Money",
    location: "Sidi Maarouf",
    address: "3 Technopark, Casablanca",
    stage: "Underwriting",
    bankableScore: 704,
    pd: 0.031,
    recommendedLimit: 15000,
    creditworthiness: "B",
    acceptance: 0.69,
    exposure: 16400,
    ltrRank: 3,
    entityConfidence: 0.84,
    velocity: "+12% MoM",
    revenue: 7400000,
    volatility: "Medium",
    kyc: { stabilityMonths: 9.2, locationStability: 0.86, identityConfidence: 0.9, deviceClean: 0.89 },
    pnl: {
      inflowTTM: "7.4M MAD",
      momoTrend: "+5.3%",
      expenses: [
        { label: "Float rebalancing", value: 42 },
        { label: "Rent & Utilities", value: 16 },
        { label: "Staff", value: 10 },
        { label: "Telco fees", value: 12 },
        { label: "Personal draws", value: 7 },
      ],
    },
    shap: [
      { label: "Agent uptime", impact: 21 },
      { label: "Liquidity discipline", impact: 18 },
      { label: "Engagement", impact: 14 },
      { label: "Volatility", impact: -12 },
      { label: "Late bills", impact: -9 },
    ],
  },
  {
    slug: "bahia-bakery",
    name: "Boulangerie Bahia",
    alias: "Bahia Bakery",
    sector: "Food Service",
    location: "Ain Sebaa",
    address: "88 Av. Hassan II, Casablanca",
    stage: "Approved",
    bankableScore: 768,
    pd: 0.02,
    recommendedLimit: 17000,
    creditworthiness: "A-",
    acceptance: 0.8,
    exposure: 13100,
    ltrRank: 4,
    entityConfidence: 0.9,
    velocity: "+6% MoM",
    revenue: 8600000,
    volatility: "Low",
    kyc: { stabilityMonths: 11.1, locationStability: 0.92, identityConfidence: 0.93, deviceClean: 0.95 },
    pnl: {
      inflowTTM: "8.6M MAD",
      momoTrend: "+3.8%",
      expenses: [
        { label: "Ingredients", value: 43 },
        { label: "Rent & Utilities", value: 19 },
        { label: "Staff", value: 15 },
        { label: "Delivery", value: 7 },
        { label: "Personal draws", value: 6 },
      ],
    },
    shap: [
      { label: "Daily turnover", impact: 33 },
      { label: "History depth", impact: 26 },
      { label: "App discipline", impact: 17 },
      { label: "Volatility", impact: -14 },
      { label: "Late bills", impact: -10 },
    ],
  },
  {
    slug: "oum-rabie",
    name: "Hanout Oum Rabie",
    alias: "Oum Rabie",
    sector: "Corner Shop",
    location: "Hay Hassani",
    address: "27 Rue Oum Rabie, Casablanca",
    stage: "New",
    bankableScore: 689,
    pd: 0.038,
    recommendedLimit: 8000,
    creditworthiness: "B",
    acceptance: 0.64,
    exposure: 7600,
    ltrRank: 5,
    entityConfidence: 0.79,
    velocity: "+4% MoM",
    revenue: 5200000,
    volatility: "Medium",
    kyc: { stabilityMonths: 8.4, locationStability: 0.81, identityConfidence: 0.88, deviceClean: 0.85 },
    pnl: {
      inflowTTM: "5.2M MAD",
      momoTrend: "+2.6%",
      expenses: [
        { label: "Suppliers", value: 52 },
        { label: "Rent & Utilities", value: 16 },
        { label: "Staff", value: 6 },
        { label: "Personal draws", value: 8 },
        { label: "Misc", value: 6 },
      ],
    },
    shap: [
      { label: "Footfall", impact: 18 },
      { label: "History depth", impact: 14 },
      { label: "Engagement", impact: 10 },
      { label: "Volatility", impact: -12 },
      { label: "Late bills", impact: -8 },
    ],
  },
  {
    slug: "taxi-benyahia",
    name: "Transport Benyahia",
    alias: "Taxi Benyahia",
    sector: "Mobility",
    location: "Oulad Ziane",
    address: "Gare Routière Oulad Ziane, Casablanca",
    stage: "Approved",
    bankableScore: 722,
    pd: 0.029,
    recommendedLimit: 14000,
    creditworthiness: "B+",
    acceptance: 0.71,
    exposure: 14200,
    ltrRank: 6,
    entityConfidence: 0.88,
    velocity: "+11% MoM",
    revenue: 6100000,
    volatility: "Medium",
    kyc: { stabilityMonths: 9.8, locationStability: 0.87, identityConfidence: 0.91, deviceClean: 0.9 },
    pnl: {
      inflowTTM: "6.1M MAD",
      momoTrend: "+5.7%",
      expenses: [
        { label: "Fuel & Maintenance", value: 44 },
        { label: "Lease / Garage", value: 18 },
        { label: "Staff", value: 9 },
        { label: "Fines & Misc", value: 7 },
        { label: "Personal draws", value: 6 },
      ],
    },
    shap: [
      { label: "Ride density", impact: 22 },
      { label: "On-time starts", impact: 17 },
      { label: "History depth", impact: 12 },
      { label: "Volatility", impact: -11 },
      { label: "Late bills", impact: -7 },
    ],
  },
];
